# Generated by Django 4.2.1 on 2023-05-12 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('direccionFacturacion', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioProducto',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metPago', models.CharField(max_length=50)),
                ('dirEnvio', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('idDetalleCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.compra')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('idDetalleProducto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costoEnvio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionEnvio',
            fields=[
                ('idEnvio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('costoEnvio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombreProducto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('idDetalleDeCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detallecompra')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proveedor'),
        ),
    ]
